name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Update dependencies
        run: |
          pip-compile --upgrade requirements.txt
          pip-compile --upgrade requirements-dev.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): update dependencies"
          title: "chore(deps): update dependencies"
          body: |
            Automated dependency updates.
            
            This PR was created automatically by the dependency update workflow.
            Please review the changes and merge if everything looks good.
          branch: "chore/update-dependencies"
          base: "master"
          labels: "dependencies" 